######################################################################
# Automatically generated by qmake (3.0) Thu Sep 7 10:46:14 2017
######################################################################

#qt
QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = carlife_test

#CONFIG -= qt
#CONFIG += debug

DESTDIR = bin
RCC_DIR += tmp
MOC_DIR += tmp
OBJECTS_DIR += tmp

#circle buffer
INCLUDEPATH += ./circle_buffer

#vpu player
INCLUDEPATH += ./vpu_player
INCLUDEPATH += ./vpu_player/include
INCLUDEPATH += ./vpu_player/include/linux

#carlife mofules
INCLUDEPATH +=  ./carlife_modules/CarlifeMgr \
                ./carlife_modules/Common \
                ./carlife_modules/InputService \
                ./carlife_modules/MediaService \
                ./carlife_modules/MessageService \
                ./carlife_modules/NaviService \
                ./carlife_modules/ScreenService \
                ./carlife_modules/SessionMgr \
                ./carlife_modules/TelService \
                ./carlife_modules/VrService

#carlife source
INCLUDEPATH += /home/imx6-solo/sdk/carlife/include

#vpu
LIBS += -lvpu

#pthread
LIBS += -lpthread

#protobuf
LIBS += -L/home/imx6-solo/sdk/protobuf-install/lib -lprotobuf

#carlife
LIBS += -L/home/imx6-solo/sdk/carlife/lib -lcarlifevehicle

#debug C++
QMAKE_CXXFLAGS += -g
#debug c
QMAKE_CFLAGS += -g

# Input
HEADERS += carlife_test/mcarlifedlg.h \
           circle_buffer/circle_buffer.h \
           vpu_player/vpudec_sdk.h \
           carlife_modules/CarlifeMgr/Carlife.h \
           carlife_modules/Common/CarlifeCommonType.h \
           carlife_modules/Common/CarlifeDebug.h \
           carlife_modules/InputService/InputCb.h \
           carlife_modules/InputService/InputService.h \
           carlife_modules/MediaService/MediaCb.h \
           carlife_modules/MediaService/MediaService.h \
           carlife_modules/MessageService/MessageService.h \
           carlife_modules/NaviService/NaviCb.h \
           carlife_modules/NaviService/NaviService.h \
           carlife_modules/ScreenService/ScreenCb.h \
           carlife_modules/ScreenService/ScreenService.h \
           carlife_modules/SessionMgr/SessionCb.h \
           carlife_modules/SessionMgr/SessionMgr.h \
           carlife_modules/TelService/TelCb.h \
           carlife_modules/TelService/TelService.h \
           carlife_modules/VrService/VrCb.h \
           carlife_modules/VrService/VrService.h \
           circle_buffer/lcthw/bstrlib.h \
           circle_buffer/lcthw/dbg.h \
           circle_buffer/lcthw/ringbuffer.h \
           vpu_player/include/v4ldisplay.h \
           vpu_player/include/vpudecodec.h \
           vpu_player/include/vpuplayer_config.h \
           vpu_player/include/linux/ipu.h \
           vpu_player/include/linux/mxcfb.h \
           vpu_player/include/linux/vpu_io.h \
           vpu_player/include/linux/vpu_lib.h
SOURCES += carlife_test/carlife_test.cpp \
           carlife_test/mcarlifedlg.cpp \
           circle_buffer/circle_buffer.c \
           vpu_player/vpudec_sdk.c \
           carlife_modules/CarlifeMgr/Carlife.cpp \
           carlife_modules/InputService/InputService.cpp \
           carlife_modules/MediaService/MediaService.cpp \
           carlife_modules/MessageService/MessageService.cpp \
           carlife_modules/NaviService/NaviService.cpp \
           carlife_modules/ScreenService/ScreenService.cpp \
           carlife_modules/SessionMgr/SessionMgr.cpp \
           carlife_modules/TelService/TelService.cpp \
           carlife_modules/VrService/VrService.cpp \
           circle_buffer/lcthw/bstrlib.c \
           circle_buffer/lcthw/ringbuffer.c \
           vpu_player/src/v4ldisplay.c \
           vpu_player/src/vpudecodec.c
