#ifndef __CARLIFE_COMMON_TYPE_H__
#define __CARLIFE_COMMON_TYPE_H__

typedef enum
{
    STATE_CHANGE_SUCCESS,
    STATE_CHANGE_FAILURE,
    STATE_CHANGE_INVALID
}STATE_CHANGE_RESULT;

#endif //__CARLIFE_COMMON_TYPE_H__
